# Generated by Django 5.0.6 on 2024-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dklead_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
